# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flytectl < Formula
  desc "FlyteCtl is a command line tool to interact with a Flyte cluster."
  homepage "https://docs.flyte.org/projects/flytectl"
  version "2.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evalsocket/flytectl/releases/download/v2.0.0/flytectl_Darwin_x86_64.tar.gz"
      sha256 "96f586e9fbd3d69bf4443d9dcea41a87429927f31c874ba560701e9d83f0039d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/evalsocket/flytectl/releases/download/v2.0.0/flytectl_Linux_x86_64.tar.gz"
      sha256 "51ce53a4131ee49186d4b6d091d19e37f33d88437946ad5a1d31ee489480c5c0"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evalsocket/flytectl/releases/download/v2.0.0/flytectl_Linux_arm64.tar.gz"
      sha256 "eb9e606b0cc275f51ca4c65bd103b49d9bd3eaaad54c45f5fbc17d64550b2246"
    end
  end

  depends_on "go"

  def install
    bin.install "flytectl"
  end
end
